#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend whalesjeremy.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 517631-web-01 100.27.4.143:80
        server 517631-web-02 100.26.215.234:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
