#!/usr/bin/env bash

# Remove the symbolic link to the default configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration file for port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the nginx service to apply the changes
service nginx restart

